In [1]:
import torch, torchvision

In [2]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [3]:
prediction = model(data)

In [9]:
loss = (prediction - labels).sum()

In [10]:
loss.backward()

In [11]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [12]:
optim.step()

In [16]:
a = torch.tensor([2.0, 3.0], requires_grad=True)
b = torch.tensor([6.0, 4.0], requires_grad=True)

In [17]:
Q = 3 * a**3 - b**2

In [20]:
external_grad = torch.tensor([1., 1.])

In [21]:
Q.backward(gradient=external_grad)

In [22]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [23]:
a.grad

tensor([36., 81.])

In [24]:
b.grad

tensor([-12.,  -8.])

In [25]:
-2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

In [26]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

In [27]:
a = x + y
a.requires_grad

False

In [28]:
b = x + z

In [29]:
b.requires_grad

True

In [30]:
from torch import nn, optim

In [31]:
model = torchvision.models.resnet18(pretrained=True)

In [32]:
for param in model.parameters():
    param.requires_grad = False

In [33]:
model.fc = nn.Linear(512, 10)

In [34]:
optimizer = optim.SGD(model.fc.parameters(), lr=1e-2, momentum=0.9)