In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [5]:
x_rand

tensor([[0.3354, 0.0606],
        [0.4191, 0.5054]])

In [6]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [9]:
rand_tensor

tensor([[0.8784, 0.8071, 0.4559],
        [0.2983, 0.6885, 0.9528]])

In [10]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
tensor = torch.rand(3,4)

In [13]:
tensor.shape

torch.Size([3, 4])

In [14]:
tensor.dtype

torch.float32

In [15]:
tensor.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [17]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0

In [18]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

In [20]:
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [21]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [22]:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [24]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [27]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [28]:
t = torch.ones(5)

In [29]:
t

tensor([1., 1., 1., 1., 1.])

In [31]:
n = t.numpy()

In [32]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [34]:
t

tensor([2., 2., 2., 2., 2.])

In [35]:
n = np.ones(5)

In [36]:
n

array([1., 1., 1., 1., 1.])

In [37]:
t = torch.from_numpy(n)

In [38]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [39]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [40]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [41]:
n

array([2., 2., 2., 2., 2.])